# Generated by Django 3.0.5 on 2020-05-13 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task_tracker.Category'),
        ),
    ]
