# Generated by Django 3.0.5 on 2020-05-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0001_initial'),
        ('users', '0002_auto_20200515_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_tasks',
            field=models.ManyToManyField(to='task_tracker.Task'),
        ),
    ]
