# Generated by Django 3.0.5 on 2020-05-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0001_initial'),
        ('users', '0002_auto_20200513_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preferences',
        ),
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.ManyToManyField(to='task_tracker.Category'),
        ),
    ]
