# Generated by Django 3.0.5 on 2020-05-07 22:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.TimeField(default=django.utils.timezone.now)),
                ('tasks', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='task_tracker.Tasks')),
            ],
        ),
    ]
