# Generated by Django 3.0.5 on 2020-05-08 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_start',
            new_name='date_posted',
        ),
    ]
