# Generated by Django 3.0.5 on 2020-05-10 05:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='BuiltInTask',
        ),
        migrations.RenameField(
            model_name='builtintask',
            old_name='date_posted',
            new_name='date_created',
        ),
        migrations.CreateModel(
            name='CustomTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_start', models.DateTimeField(default=datetime.datetime.now)),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now)),
                ('duration', models.TimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
