# Generated by Django 3.0.5 on 2020-05-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0002_auto_20200512_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('sports', 'Sports'), ('games', 'Games'), ('cooking', 'Cook'), ('custom', 'Custom')], default='custom', max_length=20, unique=True),
        ),
    ]
