# Generated by Django 3.0.5 on 2020-05-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0003_auto_20200512_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Games', 'Games'), ('Cook', 'Cook'), ('Custom', 'Custom')], default='Custom', max_length=20, unique=True),
        ),
    ]
